### ISSUE TITLE
Issue in building Wirepas Gateway Transport Service

### ISSUE THREAD

**Issue by khaleel453** [wirepas/gateway#253]
Hi

I'm facing below issue in building Transport service .

command :  pip install [-e] .

error :
(wirepas_gateway-1.4.2) root@arm:~/wirepas_gateway-1.4.2#  pip install [-e] .
ERROR: Exception:
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/wirepas_gateway-1.4.2-haZv1Frw/lib/python3.9/site-packages/pip/_vendor/packaging/requirements.py", line 102, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/root/.local/share/virtualenvs/wirepas_gateway-1.4.2-haZv1Frw/lib/python3.9/site-packages/pip/_vendor/pyparsing/core.py", line 1141, in parse_string
    raise exc.with_traceback(None)
pip._vendor.pyparsing.exceptions.ParseException: Expected string_end, found '['  (at char 11), (line:1, col:12)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/wirepas_gateway-1.4.2-haZv1Frw/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 169, in exc_logging_wrapper
    status = run_func(*args)
  File "/root/.local/share/virtualenvs/wirepas_gateway-1.4.2-haZv1Frw/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 248, in wrapper
    return func(self, options, args)
  File "/root/.local/share/virtualenvs/wirepas_gateway-1.4.2-haZv1Frw/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 342, in run
    reqs = self.get_requirements(args, options, finder, session)
  File "/root/.local/share/virtualenvs/wirepas_gateway-1.4.2-haZv1Frw/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 411, in get_requirements
    req_to_add = install_req_from_line(
  File "/root/.local/share/virtualenvs/wirepas_gateway-1.4.2-haZv1Frw/lib/python3.9/site-packages/pip/_internal/req/constructors.py", line 395, in install_req_from_line
    parts = parse_req_from_line(name, line_source)
  File "/root/.local/share/virtualenvs/wirepas_gateway-1.4.2-haZv1Frw/lib/python3.9/site-packages/pip/_internal/req/constructors.py", line 332, in parse_req_from_line
    extras = convert_extras(extras_as_string)
  File "/root/.local/share/virtualenvs/wirepas_gateway-1.4.2-haZv1Frw/lib/python3.9/site-packages/pip/_internal/req/constructors.py", line 57, in convert_extras
    return get_requirement("placeholder" + extras.lower()).extras
  File "/root/.local/share/virtualenvs/wirepas_gateway-1.4.2-haZv1Frw/lib/python3.9/site-packages/pip/_internal/utils/packaging.py", line 45, in get_requirement
    return Requirement(req_string)
  File "/root/.local/share/virtualenvs/wirepas_gateway-1.4.2-haZv1Frw/lib/python3.9/site-packages/pip/_vendor/packaging/requirements.py", line 104, in __init__
    raise InvalidRequirement(
pip._vendor.packaging.requirements.InvalidRequirement: Parse error at "'[-e]'": Expected string_end
(wirepas_gateway-1.4.2) root@arm:~/wirepas_gateway-1.4.2# 

Can some one help me out in building Transport service instead of using pre built service.  
Regards
khaleel

**Comment by GwendalRaoul** [comment]
Hello Khaleel,

As on many example from Linux manual, the optional fields are mentioned between square bracket. But when you want to use the option, you must not type it.

So your command should be:
 **pip install -e .**

This is what the system tell you with the error:
_pip._vendor.pyparsing.exceptions.ParseException: Expected string_end, found '[' (at char 11), (line:1, col:12)_

Best regards,
Gwendal

**Comment by khaleel453** [comment]
Hi,
Thanks for the update.

With the above  command i am able to install python-transport.
But when i try to run any of the commands from (wm-dbus-print,  wm-gw,   wm-node-conf)

`root@arm:~# wm-dbus-print 
Traceback (most recent call last):
  File "/usr/bin/wm-dbus-print", line 33, in <module>
    sys.exit(load_entry_point('wirepas-gateway', 'console_scripts', 'wm-dbus-print')())
  File "/usr/bin/wm-dbus-print", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.9/importlib/metadata.py", line 524, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.9/importlib/metadata.py", line 187, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: wirepas-gateway
`

Is there any particular location in which i need to install my custom python wheel or am i missing some thing .

Regards
khaleel
